name: Delete Static Web App on Azure

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  delete:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Delete Static Web App
        uses: azure/CLI@v1
        with:
          azcliversion: 2.37.0
          inlineScript: |
            az staticwebapp delete -n "$GITHUB_HEAD_REF" -g bestofui5 --yes
