name: Create Demo Apps

on:
  workflow_dispatch:

jobs:
  openui5-sample-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: SAP/openui5-sample-app
      - name: use node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install
        run: npm install
      - name: build
        run: npm run build-self-contained
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.azuresecret_openui5_sample_app }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_api_build: true
          skip_app_build: true
          app_location: "dist" # App source code path
          output_location: "" # Built app content directory - optional
          is_static_export: true
  ui5-typescript-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: SAP-samples/ui5-typescript-helloworld
      - name: use node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install
        run: npm install
      - name: build
        run: npm run build:opt
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.azuresecret_ui5_typescript_helloworld }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_api_build: true
          skip_app_build: true
          app_location: "dist" # App source code path
          output_location: "" # Built app content directory - optional
          is_static_export: true
